



import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Vipprow Digital Marketing | Beauty Academy Growth Portfolio",
  description:
    "We help beauty academies grow their admissions, brand value, social presence and online enquiries through premium digital marketing, content creation, website development and lead generation.",
  keywords: "beauty academy marketing, digital marketing beauty academy, meta ads beauty school, beauty academy website, Vipprow",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}

// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">{children}</body>
//     </html>
//   );
// }
